{
  "targets": [
    {
      "target_name": "qjsc_20210327",
      "sources": [
        "src/qjsc_20210327.cc",
        "deps/quickjs/src/cutils.c",
        "deps/quickjs/src/libregexp.c",
        "deps/quickjs/src/libunicode.c",
        "deps/quickjs/src/core/string.c",
        "deps/quickjs/src/core/function.c",
        "deps/quickjs/src/core/memory.c",
        "deps/quickjs/src/core/bytecode.c",
        "deps/quickjs/src/core/object.c",
        "deps/quickjs/src/core/exception.c",
        "deps/quickjs/src/core/gc.c",
        "deps/quickjs/src/core/malloc.c",
        "deps/quickjs/src/core/shape.c",
        "deps/quickjs/src/core/parser.c",
        "deps/quickjs/src/core/convertion.c",
        "deps/quickjs/src/core/runtime.c",
        "deps/quickjs/src/core/module.c",
        "deps/quickjs/src/core/ic.c",
        "deps/quickjs/src/core/builtins/js-array.c",
        "deps/quickjs/src/core/builtins/js-async-function.c",
        "deps/quickjs/src/core/builtins/js-async-generator.c",
        "deps/quickjs/src/core/builtins/js-atomics.c",
        "deps/quickjs/src/core/builtins/js-big-num.c",
        "deps/quickjs/src/core/builtins/js-boolean.c",
        "deps/quickjs/src/core/builtins/js-date.c",
        "deps/quickjs/src/core/builtins/js-function.c",
        "deps/quickjs/src/core/builtins/js-generator.c",
        "deps/quickjs/src/core/builtins/js-json.c",
        "deps/quickjs/src/core/builtins/js-map.c",
        "deps/quickjs/src/core/builtins/js-math.c",
        "deps/quickjs/src/core/builtins/js-number.c",
        "deps/quickjs/src/core/builtins/js-object.c",
        "deps/quickjs/src/core/builtins/js-closures.c",
        "deps/quickjs/src/core/builtins/js-operator.c",
        "deps/quickjs/src/core/builtins/js-promise.c",
        "deps/quickjs/src/core/builtins/js-proxy.c",
        "deps/quickjs/src/core/builtins/js-reflect.c",
        "deps/quickjs/src/core/builtins/js-regexp.c",
        "deps/quickjs/src/core/builtins/js-string.c",
        "deps/quickjs/src/core/builtins/js-symbol.c",
        "deps/quickjs/src/core/builtins/js-typed-array.c",
        "deps/quickjs/src/libbf.c",
      ],
      'include_dirs': [
        "<!(node -p \"require('node-addon-api').include_dir\")",
        "deps/quickjs/include",
      ],
      "defines": [
        'CONFIG_VERSION=\"2021-03-27\"'
      ],
      'cflags!': [ '-fexceptions' ],
      'cflags_cc!': [ '-fexceptions', ],
      'cflags': [ '-Wno-sign-compare' ],
      'conditions': [
        ["OS=='win'", {
          "defines": [
            "_HAS_EXCEPTIONS=1",
            "HAVE_STRUCT_TIMESPEC=1"
          ],
          "msvs_settings": {
            "VCCLCompilerTool": {
              "ExceptionHandling": 1,
              'AdditionalOptions': [ '/std:c11', '/Zc:preprocessor', ],
            },
          },
          "sources": [
            "src/qjsc_20210327.cc",

            "deps/quickjs/src/cutils.c",
            "deps/quickjs/src/libregexp.c",
            "deps/quickjs/src/libunicode.c",
            "deps/quickjs/src/core/string.c",
            "deps/quickjs/src/core/function.c",
            "deps/quickjs/src/core/memory.c",
            "deps/quickjs/src/core/bytecode.c",
            "deps/quickjs/src/core/object.c",
            "deps/quickjs/src/core/exception.c",
            "deps/quickjs/src/core/gc.c",
            "deps/quickjs/src/core/malloc.c",
            "deps/quickjs/src/core/shape.c",
            "deps/quickjs/src/core/parser.c",
            "deps/quickjs/src/core/convertion.c",
            "deps/quickjs/src/core/runtime.c",
            "deps/quickjs/src/core/module.c",
            "deps/quickjs/src/core/ic.c",
            "deps/quickjs/src/core/builtins/js-array.c",
            "deps/quickjs/src/core/builtins/js-async-function.c",
            "deps/quickjs/src/core/builtins/js-async-generator.c",
            "deps/quickjs/src/core/builtins/js-atomics.c",
            "deps/quickjs/src/core/builtins/js-big-num.c",
            "deps/quickjs/src/core/builtins/js-boolean.c",
            "deps/quickjs/src/core/builtins/js-date.c",
            "deps/quickjs/src/core/builtins/js-function.c",
            "deps/quickjs/src/core/builtins/js-generator.c",
            "deps/quickjs/src/core/builtins/js-json.c",
            "deps/quickjs/src/core/builtins/js-map.c",
            "deps/quickjs/src/core/builtins/js-math.c",
            "deps/quickjs/src/core/builtins/js-number.c",
            "deps/quickjs/src/core/builtins/js-object.c",
            "deps/quickjs/src/core/builtins/js-closures.c",
            "deps/quickjs/src/core/builtins/js-operator.c",
            "deps/quickjs/src/core/builtins/js-promise.c",
            "deps/quickjs/src/core/builtins/js-proxy.c",
            "deps/quickjs/src/core/builtins/js-reflect.c",
            "deps/quickjs/src/core/builtins/js-regexp.c",
            "deps/quickjs/src/core/builtins/js-string.c",
            "deps/quickjs/src/core/builtins/js-symbol.c",
            "deps/quickjs/src/core/builtins/js-typed-array.c",
            "deps/quickjs/src/libbf.c",

            "compat/win32/pthreads/attr.c",
            "compat/win32/pthreads/barrier.c",
            "compat/win32/pthreads/cancel.c",
            "compat/win32/pthreads/cleanup.c",
            "compat/win32/pthreads/condvar.c",
            "compat/win32/pthreads/create.c",
            "compat/win32/pthreads/dll.c",
            "compat/win32/pthreads/exit.c",
            "compat/win32/pthreads/fork.c",
            "compat/win32/pthreads/global.c",
            "compat/win32/pthreads/misc.c",
            "compat/win32/pthreads/mutex.c",
            "compat/win32/pthreads/private.c",
            "compat/win32/pthreads/rwlock.c",
            "compat/win32/pthreads/sched.c",
            "compat/win32/pthreads/semaphore.c",
            "compat/win32/pthreads/spin.c",
            "compat/win32/pthreads/sync.c",
            "compat/win32/pthreads/tsd.c",
            "compat/win32/pthreads/nonportable.c",
            "compat/win32/pthreads/errno.c",
            "compat/win32/pthreads/signal.c",
            "compat/win32/pthreads/autostatic.c",
          ],
          'include_dirs': [
            "<!(node -p \"require('node-addon-api').include_dir\")",
            "deps/quickjs/include",
            "compat/win32/pthreads",
            "compat/win32/atomic"
          ],
        }],
        ["OS=='linux'", {
          'cflags_cc': ['-fvisibility=hidden'],
          "defines": [
            "NAPI_DISABLE_CPP_EXCEPTIONS"
          ],
        }],
        ["OS=='mac'", {
          'cflags_cc': ['-fvisibility=hidden'],
          'xcode_settings': {
            'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
            'CLANG_CXX_LIBRARY': 'libc++',
            'MACOSX_DEPLOYMENT_TARGET': '10.7',
            'GCC_SYMBOLS_PRIVATE_EXTERN': 'YES',
            "OTHER_CFLAGS": [ '-Wno-sign-compare' ],
          },
        }],
  ],
    }
  ]
}
